/**
 * Wire protocol -- a JS port of companion_app/protocol.py, encoding to the
 * exact same bytes firmware/map_data.cpp expects. Keep all three in sync
 * by hand if the packet format ever changes.
 *
 * Packet layout on the BLE characteristic: [1-byte packet type][payload...]
 * Map payload layout (no packet header, built by buildMapPayload):
 *   uint16  numRoutePts
 *   numRoutePts * (int16 x, int16 y)      -- half-meter fixed point
 *   uint16  numStubs
 *   numStubs * (int16 x1, int16 y1, int8 dx, int8 dy)
 *
 * Side stubs aren't generated by this app yet (see webapp/README roadmap),
 * so buildMapPayload is always called with an empty stub list today --
 * the encoding is kept here anyway so the wire format stays byte-for-byte
 * compatible with the existing firmware without any firmware changes.
 */
import { COORD_SCALE } from './config.js';

export const PacketType = Object.freeze({
  MAP_START: 0x01,
  TELEMETRY: 0x02,
  MAP_CHUNK: 0x03,
  MAP_END: 0x04,
});

// 1 header byte + 3x float32 (x, y, heading_deg) -- used once phase 3 (live
// telemetry) lands; included now so protocol.js fully mirrors protocol.py.
export const TELEMETRY_PACKET_SIZE = 13;

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

/** One coordinate (meters) -> little-endian int16, half-meter resolution. */
export function encodeCoord(valueM) {
  const fixed = clamp(Math.round(valueM * COORD_SCALE), -32768, 32767);
  const buf = new ArrayBuffer(2);
  new DataView(buf).setInt16(0, fixed, true);
  return new Uint8Array(buf);
}

/** A short delta (meters, e.g. a stub endpoint) -> little-endian int8. */
export function encodeDelta(valueM) {
  const fixed = clamp(Math.round(valueM * COORD_SCALE), -128, 127);
  const buf = new ArrayBuffer(1);
  new DataView(buf).setInt8(0, fixed);
  return new Uint8Array(buf);
}

function concatBytes(chunks) {
  const total = chunks.reduce((sum, c) => sum + c.length, 0);
  const out = new Uint8Array(total);
  let offset = 0;
  for (const chunk of chunks) {
    out.set(chunk, offset);
    offset += chunk.length;
  }
  return out;
}

/**
 * @param {{x:number, y:number}[]} routePoints  local (x, y) meters
 * @param {{from:{x:number,y:number}, to:{x:number,y:number}}[]} stubs
 * @returns {Uint8Array} raw map payload, no packet header
 */
export function buildMapPayload(routePoints, stubs = []) {
  const parts = [];

  const routeCountBuf = new ArrayBuffer(2);
  new DataView(routeCountBuf).setUint16(0, routePoints.length, true);
  parts.push(new Uint8Array(routeCountBuf));

  for (const { x, y } of routePoints) {
    parts.push(encodeCoord(x));
    parts.push(encodeCoord(y));
  }

  const stubCountBuf = new ArrayBuffer(2);
  new DataView(stubCountBuf).setUint16(0, stubs.length, true);
  parts.push(new Uint8Array(stubCountBuf));

  for (const stub of stubs) {
    parts.push(encodeCoord(stub.from.x));
    parts.push(encodeCoord(stub.from.y));
    parts.push(encodeDelta(stub.to.x - stub.from.x));
    parts.push(encodeDelta(stub.to.y - stub.from.y));
  }

  return concatBytes(parts);
}

/** [0x02][x:f32][y:f32][heading:f32] = 13 bytes, little-endian. */
export function buildTelemetryPacket(x, y, headingDeg) {
  const buf = new ArrayBuffer(TELEMETRY_PACKET_SIZE);
  const view = new DataView(buf);
  view.setUint8(0, PacketType.TELEMETRY);
  view.setFloat32(1, x, true);
  view.setFloat32(5, y, true);
  view.setFloat32(9, headingDeg, true);
  return new Uint8Array(buf);
}
